name: Run playwright tests against stage
on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  schedule:
    - cron: "0 0 * * *" # This cron expression runs the action every 24 hours at midnight UTC
  workflow_dispatch:

concurrency:
  group: integration-group
  cancel-in-progress: true
jobs:
  Playwright-integration-test:
    runs-on:
      - codebuild-content-services-integration-repo-${{ github.run_id }}-${{ github.run_attempt }}
      - instance-size:small
      - buildspec-override:true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache - node_modules
        if: ${{ !cancelled() }}
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            dist
          key: ${{ runner.os }}-frontend-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-frontend-node-modules-

      - name: Cache Playwright browsers
        if: ${{ !cancelled() }}
        id: cache-playwright-browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('playwright.config.ts') }}
          restore-keys: ${{ runner.os }}-playwright-

      - name: Create .env file
        run: |
          echo "USER1USERNAME=$USER1USERNAME" >> .env
          echo "USER1PASSWORD=$USER1PASSWORD" >> .env
          echo "BASE_URL=$BASE_URL" >> .env
          echo "PROXY=$PROXY" >> .env
          echo "TOKEN=apple" >> .env
          echo "CI=true" >> .env

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: yarn install

      - name: Get front-end/backend-tests
        run: yarn get-tests

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        env:
          CURRENTS_PROJECT_ID: ${{ secrets.CURRENTS_PROJECT_ID }}
          CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}
        run: yarn playwright test

      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: "./playwright-ctrf/playwright-ctrf.json"
        if: ${{ !cancelled() }}

      - name: Store report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./playwright-ctrf
          retention-days: 10
